### ISSUE TITLE
too few arguments to function upon make of file

### ISSUE THREAD

**Issue by teddiebean** [tihmstar/usbmuxd2#28]
Getting this error on two separate systems and instances when trying to make the file, always comes up with the same error information, see below - always combination of error 1 and error 2

`~/usbmuxd2 $ make
make  all-recursive
make[1]: Entering directory '/home/pi/usbmuxd2'
Making all in usbmuxd2
make[2]: Entering directory '/home/pi/usbmuxd2/usbmuxd2'
g++ -DHAVE_CONFIG_H -I. -I..       -I../usbmuxd2  -I/usr/local/include -I/usr/include/libusb-1.0  -I/usr/local/include -g -O2 -DCUSTOM_LOGGING="\"log.h\"" -std=c++17 -g -O0 -DDEBUG=1 -MT usbmuxd-Client.o -MD -MP -MF .deps/usbmuxd-Client.Tpo -c -o usbmuxd-Client.o `test -f 'Client.cpp' || echo './'`Client.cpp
Client.cpp: In member function ‘void Client::processData(const usbmuxd_header*)’:
Client.cpp:292:96: error: too few arguments to function ‘plist_err_t plist_from_memory(const char*, uint32_t, void**, plist_format_t*)’
  292 |                     plist_from_memory(pairRecord, (uint32_t)pairRecord_len, &p_parsedPairRecord);
      |                                                                                                ^
In file included from Client.hpp:15,
                 from Client.cpp:8:
/usr/local/include/plist/plist.h:846:27: note: declared here
  846 |     PLIST_API plist_err_t plist_from_memory(const char *plist_data, uint32_t length, plist_t *plist, plist_format_t *format);
      |                           ^~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:633: usbmuxd-Client.o] Error 1
make[2]: Leaving directory '/home/pi/usbmuxd2/usbmuxd2'
make[1]: *** [Makefile:432: all-recursive] Error 1
make[1]: Leaving directory '/home/pi/usbmuxd2'
make: *** [Makefile:364: all] Error 2`

**Comment by sepsky** [comment]
I edited the `Client.cpp` and `sysconf.cpp‎` so that I pass the following in: 
```
plist_format_t format = PLIST_FORMAT_NONE;
plist_from_memory(pairRecord, record_len, &p_parsedPairRecord, &format);
```
The error is due to a breaking change. the `plist_from_memory` now also needs a format parameter passed in.
(have a look at `plist_format_t`, I passed `PLIST_FORMAT_NONE` but you can pass `PLIST_FORMAT_JSON`and `PLIST_FORMAT_XML` as well, but check the values of the enum in case)

**Comment by teddiebean** [comment]
How do I check the values to ensure the correct type is passed in?

Which files do I need to make the changes in?

**Comment by sepsky** [comment]
you need to make the changes in the files you have errors. From the logs you posted above, the issue is in `Client.pp`, inside the `usbmuxd2` folder within the root `usbmuxd2` folder (the root is the folder git creates when you clone). So for example, if you've cloned the repo in `~/Documents`, it'll be `~/Documents/usbmuxd2/usbmuxd2/Client.cpp`.

If you do a search of your repo for that `plist_from_memory`, you should be finding 2 instances of its execution. Those are the places I found.
