### ISSUE TITLE
error: wifi support requested but no wifi backend could not be found

### ISSUE THREAD

**Issue by mcdull** [tihmstar/usbmuxd2#7]
The captioned error happened on ./autogen.sh. after the "checking for avahi... no" messge.
My linux box is a vm with no wifi module, is it still possible to run usbmuxd2?  
My ultimate goal is to be able to sync and backup my ios devices in this linux vm. Thanks.

**Comment by truonggiang0710** [comment]
Yes, I get the issue too. So please help to resolve it @tihmstar .

**Comment by eriklangemeijer** [comment]
The line above probably says
`checking for avahi... no` which matches the requirement `avahi-client (WIFI)`
I solved this by installing this lib using:
`sudo apt install libavahi-client-dev`

**Comment by jkcoxson** [comment]
Were you guys ever able to get WiFi working on Linux? I’m only able to get it to go over USB on my box.

**Comment by bentumbler** [comment]
Turns out that it is specifically looking for avahi-client >= 0.7.

If the following output fails then you need to get the right version (for me on my older rPi meant I needed to build avahi from source). It was a pain too because the removal of the existing avahi didn't remove avahi-client and you will need to run export PKG_CONFIG_PATH=/usr/local/lib to point to the correct client.

pkg-config --print-errors --exists 'avahi-client >= 0.7'

**Comment by bentumbler** [comment]
> Were you guys ever able to get WiFi working on Linux? I’m only able to get it to go over USB on my box.

Yes, eventually
